services:
  web_api:
    build:
      context: .
      # dockerfile: Dockerfile
      dockerfile: Dockerfile.dev
    container_name: web_api_application
    ports:
      - "5000:80"
      - "5069:80"
    volumes:
      - ./Authorization:/src/Authorization
      - ./Controllers:/src/Controllers
      - ./Data:/src/Data
      - ./Entities:/src/Entities
      - ./Helpers:/src/Helpers
      - ./Models:/src/Models
      - ./Properties:/src/Properties
      - ./Services:/src/Services
      - ./Program.cs:/src/Program.cs
    depends_on:
      - sql
      - mongo
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: uzer
      MONGO_INITDB_ROOT_PASSWORD: pazzwurd
    volumes:
      - ./db_data/:/data/db/