// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Helpers;

#nullable disable

namespace WebApi.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDataContext))]
    [Migration("20220106030852_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
            modelBuilder.Entity("WebApi.Data.Product", b =>
         {
             b.Property<int>("ProductId")
                 .ValueGeneratedOnAdd()
                 .HasColumnType("INTEGER");

             SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

             b.Property<string>("Name")
                 .HasColumnType("TEXT");

             b.Property<int>("ProductCategory")
                 .HasColumnType("INTEGER");

             b.Property<string>("Description")
                 .HasColumnType("TEXT");

             b.Property<decimal>("Price")
                 .HasColumnType("INTEGER");

             b.Property<string>("SKU")
                 .HasColumnType("TEXT");
             b.Property<string>("Code")
                 .HasColumnType("TEXT");

             b.HasKey("ProductId");

             b.ToTable("Products");
         });
#pragma warning restore 612, 618
        }
    }
}
